### ISSUE TITLE
Didn't work on 2.82

### ISSUE THREAD

**Issue by Zakallenko** [Protinon/Blender-rpc#1]
Error when I try to enable add-on
![image](https://user-images.githubusercontent.com/66310741/83516158-4590c800-a4df-11ea-81db-93ed2226821a.png)

**Comment by Protinon** [comment]
Hello. Did you download the addon from the “Releases” tab? Looks like you cloned the repository to a zip file.

**Comment by Zakallenko** [comment]
Oh you right. Sorry, my bad
