### ISSUE TITLE
Error on enabling Add-on

### ISSUE THREAD

**Issue by gekyxme** [Protinon/Blender-rpc#11]
![image](https://user-images.githubusercontent.com/62861873/123624609-659ed200-d82c-11eb-8397-e25a6e2f7d5e.png)

**Comment by Protinon** [comment]
Hello, I wasn't able to reproduce this bug.

Can you try deleting all installs of this addon and re-enabling? In the Blender addon panel there's an option to remove the addon. Then try re-installing using the README instructions.

**Comment by gekyxme** [comment]
Okay I had to format my PC yesterday, so I gave it another chance and it worked! Thank  you.
