### ISSUE TITLE
Making blender open slow : Blender3.0

### ISSUE THREAD

**Issue by MBlais13** [Protinon/Blender-rpc#12]
When I open blender (with the only add-on enabled being this one) it takes a while to open (disabling the add-on fixes the issue).
not a computer spec issue.

**Comment by Protinon** [comment]
I just downloaded the latest Blender 3.0 Alpha and cannot replicate this. Can you download the latest from https://builder.blender.org/download/daily/ and try again with no addons (except this)? Can you also try restarting you computer?

If that doesn't work, can you post your operating system and CPU?

**Comment by MBlais13** [comment]
(clean install) https://www.youtube.com/watch?v=nB2QGan59e8

I'm not sure what is going on but I might have found another issue, This is a clean install of blender but when I change some addons only on the first launch of blender it will load slowly then it will put it in my temp files. After that, it will sometimes load faster

**Current**
Ryzen 7 5800x
Asus RX 460 OC
16GB DDR4 3600MHz
Samsung 970 EVO 500GB

**Comment by MBlais13** [comment]
It seems like something bigger than some addon stuff, I'll have to take a closer look tomorrow though.

**Comment by MBlais13** [comment]
Turns out something is wrong with my blender as a whole, odd how I tested to see if it was the plugin like 10 times and turns out its not.
