### ISSUE TITLE
Freezes when trying to enable on 3.0.0

### ISSUE THREAD

**Issue by Najmul190** [Protinon/Blender-rpc#13]
Whenever you try enabling this on Blender 3.0.0, it just freezes blender. When you restart it still doesn't work.

**Comment by Protinon** [comment]
Can you give me your Blender hash and date (https://blender.stackexchange.com/a/148133) and are you on Windows 10?

**Comment by Najmul190** [comment]
![image](https://user-images.githubusercontent.com/68229089/146645628-4f16659f-6e88-4752-a3d3-3f9539c6b577.png)

No, I'm on Windows 11 but the addon was working fine recently.

Hash: f1cca3055776
Date: 2021-12-02 18:35

**Comment by Protinon** [comment]
Sorry about the delay. I got a VM of Windows 11 to test this, but couldn't reproduce the slowness. There was [another issue](https://github.com/Protinon/Blender-rpc/issues/12) similar to this, but the answer wasn't clear. Maybe the OP for that issue can comment on this for possible solutions. I'll reach out to them.

**Comment by Najmul190** [comment]
Just tested again, and for some reason it now works. It must've been something else on my PC interrupting it I guess. Thanks though.
