### ISSUE TITLE
Cannot enable on Blender 3.0.0

### ISSUE THREAD

**Issue by VRXDev2** [Protinon/Blender-rpc#14]
![image](https://user-images.githubusercontent.com/98953603/152541625-eba13d33-e0ac-4b4d-922d-fce13d0ddec2.png)
That what it says when i try to enable it, im on Windows 10.

**Comment by dave9123** [comment]
It works on Blender 3.0.1

**Comment by Protinon** [comment]
I don't think this is the full error. Can you get the error to occur again and post a screenshot of everything? You'll have to open the system console to see more: https://i.stack.imgur.com/hK3bu.jpg

**Comment by Smeltie** [comment]
Just to Chime in here, i'm on 3.0.0 (Windows 11) and I haven't encountered any issues as of yet.
Works perfectly fine.
This is on a fresh install of Windows 11 (on technically unsupported hardware).
So i'm not sure this has to do with a particular version of blender.

**Comment by Protinon** [comment]
No response from OP, closing.
