### ISSUE TITLE
option for time elapsed to be time since saving

### ISSUE THREAD

**Issue by djtravz** [Protinon/Blender-rpc#17]
I have no idea if this would even be possible albeit feasible, but it would be funny if there was a timer for the time since the project was last saved

**Comment by Protinon** [comment]
It is possible, there is a "save" event available. However there are a few caveats. 

- Discord imposes a 30-second update limit on Rich presence.
- There can only be 1 timer shown, and I don't see much usefulness in a "last saved" timer opposed to the current options. 

To clarify, it could be useful in some cases, but for the vast majority it's not necessary. And it would add extra complexity to the script to rate-limit the sending of messages. I know many (including myself) save often, which could overload Discord.
