### ISSUE TITLE
cannot importpypresence from .. 2.91 beta

### ISSUE THREAD

**Issue by debpalash** [Protinon/Blender-rpc#6]
![image](https://user-images.githubusercontent.com/4178343/99354719-fabc0e80-28cc-11eb-9920-69100879db28.png)

**Comment by Protinon** [comment]
You cloned the repository, please download the .zip from the “releases” section.

**Comment by debpalash** [comment]
it was official installer what i used. How can you just throw assumption for an issue! @Protinon
