### ISSUE TITLE
Error Loading Up

### ISSUE THREAD

**Issue by Orikario** [Protinon/Blender-rpc#8]
Don't know if I'm doing something wrong but this is happening to me 
![image](https://user-images.githubusercontent.com/75096822/100391105-60756c80-302a-11eb-80c8-85fa62376eb1.png)
Edit: I'm using 2.90

**Comment by Protinon** [comment]
As I’ve said in the readme and in the issue I left open, please download from the Releases section instead of cloning the repository.
